# Generated by Django 3.2.3 on 2021-05-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(verbose_name='date published')),
                ('estimated_time', models.IntegerField(default=-1)),
                ('deliver_finish', models.BooleanField(default=0)),
                ('cancel', models.BooleanField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shops')),
            ],
        ),
    ]
